version: '3'

services:
  db:
    build:
      context: db
      dockerfile: ./Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    tty: true
    restart: always
    user: root
    volumes:
      - ./db/commands:/commands
      - ./db/data:/data
      - ./db/init:/docker-entrypoint-initdb.d
  crud:
    build:
      context: crud
      dockerfile: ./Dockerfile
    volumes:
      - ./crud:/code
    ports:
      - 8000:8000
    environment:
      - DB_NAME=studio
      - DB_USER=root
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_HOST=db
      - PGPASSWORD=postgres
    tty: true
    depends_on:
      - db