package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"time"
)

// RoomFacilities represents a row from 'public.room_facilities'.
type RoomFacilities struct {
	RoomFacilityID          int        `json:"room_facility_id"`          // room_facility_id
	FacilityID              int        `json:"facility_id"`               // facility_id
	FacilityName            string     `json:"facility_name"`             // facility_name
	RoomFacilityDescription *string    `json:"room_facility_description"` // room_facility_description
	RoomFacilityCount       *int       `json:"room_facility_count"`       // room_facility_count
	RoomFacilityPrice       *float64   `json:"room_facility_price"`       // room_facility_price
	RoomFacilityUnitHour    *float64   `json:"room_facility_unit_hour"`   // room_facility_unit_hour
	CreatedAt               time.Time  `json:"created_at"`                // created_at
	UpdatedAt               *time.Time `json:"updated_at"`                // updated_at
}

// RoomFacilitiesByRoomID runs a custom query, returning results as RoomFacilities.
func RoomFacilitiesByRoomID(ctx context.Context, db DB, roomID int) ([]*RoomFacilities, error) {
	// query
	const sqlstr = `SELECT ` +
		`rf.room_facility_id, ` +
		`rf.facility_id, ` +
		`f.facility_name, ` +
		`rf.room_facility_description, ` +
		`rf.room_facility_count, ` +
		`rf.room_facility_price, ` +
		`rf.room_facility_unit_hour, ` +
		`rf.created_at, ` +
		`rf.updated_at ` +
		`FROM ` +
		`room_facility AS rf ` +
		`LEFT JOIN ` +
		`facility AS f ` +
		`ON  rf.facility_id = f.facility_id ` +
		`WHERE ` +
		`rf.room_id = $1 ` +
		`AND rf.is_deleted IS FALSE ` +
		`;`
	// run
	logf(sqlstr, roomID)
	rows, err := db.QueryContext(ctx, sqlstr, roomID)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()
	// load results
	var res []*RoomFacilities
	for rows.Next() {
		var rf RoomFacilities
		// scan
		if err := rows.Scan(&rf.RoomFacilityID, &rf.FacilityID, &rf.FacilityName, &rf.RoomFacilityDescription, &rf.RoomFacilityCount, &rf.RoomFacilityPrice, &rf.RoomFacilityUnitHour, &rf.CreatedAt, &rf.UpdatedAt); err != nil {
			return nil, logerror(err)
		}
		res = append(res, &rf)
	}
	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}
	return res, nil
}
