from django.contrib import admin
from crud import models

# Register your models here.
admin.site.register(models.Address)
admin.site.register(models.Amenity)
admin.site.register(models.City)
admin.site.register(models.DateSlot)
admin.site.register(models.DayTemplate)
admin.site.register(models.Exit)
admin.site.register(models.Facility)
admin.site.register(models.FloorMaterial)
admin.site.register(models.Image)
admin.site.register(models.Line)
admin.site.register(models.Payment)
admin.site.register(models.Prefecture)
admin.site.register(models.Railway)
admin.site.register(models.Reservation)
admin.site.register(models.Room)
admin.site.register(models.RoomFacility)
admin.site.register(models.RoomFloorMaterial)
admin.site.register(models.RoomImage)
admin.site.register(models.RoomSlot)
admin.site.register(models.Slot)
admin.site.register(models.SlotDayTemplate)
admin.site.register(models.Station)
admin.site.register(models.StationRailway)
admin.site.register(models.StationRailwayExit)
admin.site.register(models.StationRailwayLine)
admin.site.register(models.Studio)
admin.site.register(models.StudioAmenity)
admin.site.register(models.StudioFacility)
admin.site.register(models.StudioImage)
admin.site.register(models.StudioPayment)
admin.site.register(models.StudioReservation)
admin.site.register(models.StudioStationRailwayExit)
