from django.contrib import admin
from crud import models

# Register your models here.
admin.site.register(models.Address)
admin.site.register(models.Amenity)
admin.site.register(models.City)
admin.site.register(models.DateSlotLink)
admin.site.register(models.DayTemplate)
admin.site.register(models.Exit)
admin.site.register(models.Facility)
admin.site.register(models.FloorMaterial)
admin.site.register(models.Image)
admin.site.register(models.Line)
admin.site.register(models.Payment)
admin.site.register(models.Prefecture)
admin.site.register(models.Railway)
admin.site.register(models.Reservation)
admin.site.register(models.Room)
admin.site.register(models.RoomFacilityLink)
admin.site.register(models.RoomFloorMaterialLink)
admin.site.register(models.RoomImageLink)
admin.site.register(models.RoomSlotLink)
admin.site.register(models.Slot)
admin.site.register(models.SlotDayTemplateLink)
admin.site.register(models.Station)
admin.site.register(models.StationRailwayExitLink)
admin.site.register(models.StationRailwayLineLink)
admin.site.register(models.StationRailwayLink)
admin.site.register(models.Studio)
admin.site.register(models.StudioAccessByStationLink)
admin.site.register(models.StudioAmenityLink)
admin.site.register(models.StudioFacilityLink)
admin.site.register(models.StudioImageLink)
admin.site.register(models.StudioPaymentLink)
admin.site.register(models.StudioReservationLink)
