from rest_framework import routers
from crud import views

router = routers.DefaultRouter()
router.register(r'address', views.AddressViewSet)
router.register(r'amenity', views.AmenityViewSet)
router.register(r'city', views.CityViewSet)
router.register(r'date_slot', views.DateSlotViewSet)
router.register(r'day_template', views.DayTemplateViewSet)
router.register(r'exit', views.ExitViewSet)
router.register(r'facility', views.FacilityViewSet)
router.register(r'floor_material', views.FloorMaterialViewSet)
router.register(r'image', views.ImageViewSet)
router.register(r'line', views.LineViewSet)
router.register(r'payment', views.PaymentViewSet)
router.register(r'prefecture', views.PrefectureViewSet)
router.register(r'railway', views.RailwayViewSet)
router.register(r'reservation', views.ReservationViewSet)
router.register(r'room', views.RoomViewSet)
router.register(r'room_facility', views.RoomFacilityViewSet)
router.register(r'room_floor_material', views.RoomFloorMaterialViewSet)
router.register(r'room_image', views.RoomImageViewSet)
router.register(r'room_slot', views.RoomSlotViewSet)
router.register(r'slot', views.SlotViewSet)
router.register(r'slot_day_template', views.SlotDayTemplateViewSet)
router.register(r'station', views.StationViewSet)
router.register(r'station_railway', views.StationRailwayViewSet)
router.register(r'station_railway_exit', views.StationRailwayExitViewSet)
router.register(r'station_railway_line', views.StationRailwayLineViewSet)
router.register(r'studio', views.StudioViewSet)
router.register(r'studio_amenity', views.StudioAmenityViewSet)
router.register(r'studio_facility', views.StudioFacilityViewSet)
router.register(r'studio_image', views.StudioImageViewSet)
router.register(r'studio_payment', views.StudioPaymentViewSet)
router.register(r'studio_reservation', views.StudioReservationViewSet)
router.register(r'studio_station_railway_exit', views.StudioStationRailwayExitViewSet)
