from rest_framework import routers
from crud import views

router = routers.DefaultRouter()
router.register(r'address', views.AddressViewSet)
router.register(r'amenity', views.AmenityViewSet)
router.register(r'city', views.CityViewSet)
router.register(r'date_slot_link', views.DateSlotLinkViewSet)
router.register(r'day_template', views.DayTemplateViewSet)
router.register(r'exit', views.ExitViewSet)
router.register(r'facility', views.FacilityViewSet)
router.register(r'floor_material', views.FloorMaterialViewSet)
router.register(r'image', views.ImageViewSet)
router.register(r'line', views.LineViewSet)
router.register(r'payment', views.PaymentViewSet)
router.register(r'prefecture', views.PrefectureViewSet)
router.register(r'railway', views.RailwayViewSet)
router.register(r'reservation', views.ReservationViewSet)
router.register(r'room', views.RoomViewSet)
router.register(r'room_facility_link', views.RoomFacilityLinkViewSet)
router.register(r'room_floor_material_link', views.RoomFloorMaterialLinkViewSet)
router.register(r'room_image_link', views.RoomImageLinkViewSet)
router.register(r'room_slot_link', views.RoomSlotLinkViewSet)
router.register(r'slot', views.SlotViewSet)
router.register(r'slot_day_template_link', views.SlotDayTemplateLinkViewSet)
router.register(r'station', views.StationViewSet)
router.register(r'station_railway_exit_link', views.StationRailwayExitLinkViewSet)
router.register(r'station_railway_line_link', views.StationRailwayLineLinkViewSet)
router.register(r'station_railway_link', views.StationRailwayLinkViewSet)
router.register(r'studio', views.StudioViewSet)
router.register(r'studio_access_by_station_link', views.StudioAccessByStationLinkViewSet)
router.register(r'studio_amenity_link', views.StudioAmenityLinkViewSet)
router.register(r'studio_facility_link', views.StudioFacilityLinkViewSet)
router.register(r'studio_image_link', views.StudioImageLinkViewSet)
router.register(r'studio_payment_link', views.StudioPaymentLinkViewSet)
router.register(r'studio_reservation_link', views.StudioReservationLinkViewSet)
