@startuml

entity "スタジオ" as Studio {
    * studio_id : integer
}

entity "部屋" as Room {
    * room_id : integer
    --
    # studio_id : integer <<FK>>
}

entity "部屋日程" as RoomDate {
    * room_date_id : integer
    --
    # room_id : integer
    # date : date
}

' 部屋日程プランでroom_date_idに該当するplan_idを複数取得し、さらにbegin_timeとend_timeで検索をかけて、残ったplan_idがその枠で予約可能なプラン
entity "枠" as Quota {
    * quota_id : integer
    --
    # room_date_id : integer
    # begin_time : time
    # end_time : time
    reservation_id : integer <<FK>>
    reserved_plan_id : integer <<FK>>
}

entity "枠タイプ" as QuotaType {
    * quota_type_id : integer
    --
    # studio_id : integer <<FK>>
    * hour_per_quota : number
    * min_reservable_quotas : integer
}

entity "プラン" as Plan {
    * plan_id : integer
    --
    # quota_type_id : integer <<FK>>
    * begin_time : time
    * end_time : time
    * price : integer
}

entity "部屋日程-プラン" as RoomDatePlan {
    * room_date_id : integer <<FK>>
    * plan_id : integer <<FK>>
    --
}

entity "予約" as Reservation {
    * reservation_id : integer
    --
    * user_id : integer <<FK>>
    * transaction_id : integer
    * is_completed : boolean
    * completed_at : datetime
    * is_canceled : boolean
    * canceled_at : datetime
    * created_at : datetime
    * updated_at : datetime
}


Studio ||--|{ Room
Room ||--|{ RoomDate
Studio ||--|{ QuotaType
QuotaType ||--|{ Plan
Plan ||--|{ RoomDatePlan
RoomDate ||--|{ RoomDatePlan
RoomDate ||--|{ Quota
Reservation ||--|{ Quota
Plan ||--|{ Quota

@enduml