# Generated by Django 3.2.6 on 2021-08-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(help_text='決済方法名 (オンライン決済)。必須。', max_length=32, verbose_name='決済方法名'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(help_text='予約方法名 (サイト決済)。必須。', max_length=32, verbose_name='予約方法名'),
        ),
    ]
