# Generated by Django 3.2.6 on 2021-08-25 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210815_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefecture',
            name='id',
            field=models.CharField(help_text='都道府県ID (P01)。必須。', max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='都道府県ID'),
        ),
    ]
