# Generated by Django 4.0.1 on 2022-01-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_name', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenity_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'amenity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DateSlotLink',
            fields=[
                ('date_slot_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'date_slot_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DayTemplate',
            fields=[
                ('day_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_template_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'day_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('exit_id', models.AutoField(primary_key=True, serialize=False)),
                ('exit_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'exit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloorMaterial',
            fields=[
                ('floor_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_material_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'floor_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=512)),
                ('image_path', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('prefecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('prefecture_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'prefecture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Railway',
            fields=[
                ('railway_id', models.AutoField(primary_key=True, serialize=False)),
                ('railway_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'railway',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=512)),
                ('reservation_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('min_reservable_people', models.IntegerField(blank=True, null=True)),
                ('max_reservable_people', models.IntegerField(blank=True, null=True)),
                ('floor_area', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomFacilityLink',
            fields=[
                ('room_facility_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_facility_count', models.IntegerField(blank=True, null=True)),
                ('room_facility_price', models.FloatField(blank=True, null=True)),
                ('room_facility_unit_hour', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'room_facility_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomFloorMaterialLink',
            fields=[
                ('room_floor_material_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'room_floor_material_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomImageLink',
            fields=[
                ('room_image_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_image_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomSlotLink',
            fields=[
                ('room_slot_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('remain_slot_count', models.IntegerField()),
                ('slot_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'room_slot_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('workload', models.FloatField()),
                ('time_begin', models.TimeField()),
                ('time_end', models.TimeField()),
                ('slot_base_price', models.FloatField()),
                ('slot_count', models.IntegerField()),
            ],
            options={
                'db_table': 'slot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SlotDayTemplateLink',
            fields=[
                ('slot_day_template_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'slot_day_template_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationRailwayExitLink',
            fields=[
                ('station_railway_exit_link_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'station_railway_exit_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationRailwayLineLink',
            fields=[
                ('station_railway_line_link_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'station_railway_line_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationRailwayLink',
            fields=[
                ('station_railway_link_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'station_railway_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('studio_id', models.AutoField(primary_key=True, serialize=False)),
                ('studio_name', models.CharField(max_length=1024)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('precaution', models.TextField(blank=True, null=True)),
                ('homepage_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact', models.CharField(max_length=11)),
                ('rent_by_min_hours', models.FloatField()),
                ('can_free_cancel', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'studio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudioAccessByStationLink',
            fields=[
                ('studio_access_by_station_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('minutes_from_station', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'studio_access_by_station_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudioAmenityLink',
            fields=[
                ('studio_amenity_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('studio_amenity_count', models.IntegerField(blank=True, null=True)),
                ('studio_amenity_price', models.FloatField(blank=True, null=True)),
                ('studio_amenity_unit_hour', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'studio_amenity_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudioFacilityLink',
            fields=[
                ('studio_facility_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('studio_facility_count', models.IntegerField(blank=True, null=True)),
                ('studio_facility_price', models.FloatField(blank=True, null=True)),
                ('studio_facility_unit_hour', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'studio_facility_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudioImageLink',
            fields=[
                ('studio_image_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'studio_image_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudioPaymentLink',
            fields=[
                ('studio_payment_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'studio_payment_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudioReservationLink',
            fields=[
                ('studio_reservation_link_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'studio_reservation_link',
                'managed': False,
            },
        ),
    ]
