# Generated by Django 4.0.1 on 2022-01-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_name', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenity_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'amenity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DayTemplate',
            fields=[
                ('day_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_template_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'day_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('exit_id', models.AutoField(primary_key=True, serialize=False)),
                ('exit_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'exit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloorMaterial',
            fields=[
                ('floor_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_material_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'floor_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=512)),
                ('image_path', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('prefecture_id', models.AutoField(primary_key=True, serialize=False)),
                ('prefecture_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'prefecture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Railway',
            fields=[
                ('railway_id', models.AutoField(primary_key=True, serialize=False)),
                ('railway_name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'railway',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=512)),
                ('reservation_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('min_reservable_people', models.IntegerField(blank=True, null=True)),
                ('max_reservable_people', models.IntegerField(blank=True, null=True)),
                ('floor_area', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('room_facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_facility_serial_number', models.IntegerField()),
                ('room_facility_count', models.IntegerField(blank=True, null=True)),
                ('room_facility_price', models.FloatField(blank=True, null=True)),
                ('room_facility_unit_hour', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'room_facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomFloorMaterial',
            fields=[
                ('room_floor_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'room_floor_material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('room_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomSlot',
            fields=[
                ('room_slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_begin', models.TimeField()),
                ('time_end', models.TimeField()),
                ('workload', models.FloatField()),
                ('slot_price', models.IntegerField()),
                ('remain_slot_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'room_slot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomSlotDayTemplate',
            fields=[
                ('room_slot_day_template_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_begin', models.TimeField()),
                ('time_end', models.TimeField()),
                ('workload', models.FloatField()),
                ('slot_base_price', models.FloatField()),
                ('slot_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'room_slot_day_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationRailway',
            fields=[
                ('station_railway_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'station_railway',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationRailwayExit',
            fields=[
                ('station_railway_exit_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'station_railway_exit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StationRailwayLine',
            fields=[
                ('station_railway_line_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'station_railway_line',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('studio_id', models.AutoField(primary_key=True, serialize=False)),
                ('studio_name', models.CharField(max_length=1024)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('precaution', models.TextField(blank=True, null=True)),
                ('homepage_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('contact', models.CharField(max_length=11)),
                ('rent_by_min_hours', models.FloatField()),
                ('can_free_cancel', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'studio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudioAmenity',
            fields=[
                ('studio_amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('studio_amenity_serial_number', models.IntegerField()),
                ('studio_amenity_count', models.IntegerField(blank=True, null=True)),
                ('studio_amenity_price', models.FloatField(blank=True, null=True)),
                ('studio_amenity_unit_hour', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'studio_amenity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudioFacility',
            fields=[
                ('studio_facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('studio_facility_serial_number', models.IntegerField()),
                ('studio_facility_count', models.IntegerField(blank=True, null=True)),
                ('studio_facility_price', models.FloatField(blank=True, null=True)),
                ('studio_facility_unit_hour', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'studio_facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudioImage',
            fields=[
                ('studio_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'studio_image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudioPayment',
            fields=[
                ('studio_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'studio_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudioReservation',
            fields=[
                ('studio_reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'studio_reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudioStationRailwayExit',
            fields=[
                ('studio_station_railway_exit_id', models.AutoField(primary_key=True, serialize=False)),
                ('minutes_from_station', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'db_table': 'studio_station_railway_exit',
                'managed': False,
            },
        ),
    ]
